server:
  port: 8202
spring:
  application:
    name: order-server
  zipkin:
    base-url: http://localhost:8300

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
    register-with-eureka: true
    fetch-registry: true
