server:
  port: 80

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/

zuul:
  routes:
    api-menmber:
      path: /api-menmber/**
      serviceId: member-server
    api-order:
      path: /api-order/**
      serviceId: order-server