server:
  port: 8201
spring:
  application:
    name: member-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


